# Generated by Django 3.2.3 on 2022-01-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messag',
            new_name='ChatMessage',
        ),
    ]
